CREATE EXTENSION "uuid-ossp";

CREATE TABLE users (
  token UUID PRIMARY KEY DEFAULT uuid_generate_v4() NOT NULL,
  username VARCHAR(31) NOT NULL,
  password VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  last_login TIMESTAMP NOT NULL
);